import { TesteeType, TrainingListType } from "./types.d";

export const dummyTrainingData: TrainingListType = {
  userInfo: {
    agency_ID: "jeong",
    agency_name: "jeong.",
    testee_nickname: "홍길동",
    testee_idx: 1699,
    testee_class: "개나리반",
    user_ID: "p002",
    start_date: "2022-08-01",
    end_date: "2022-08-24",
    language: "한국어",
  },
  taskList: [
    {
      task_dayofweek: "월,화,수,목,금",
      task_enddate: "2022-08-19",
      task_generatedate: "2022-08-05",
      task_language: "한국어",
      task_level: 6,
      task_reculsivecount: 2,
      task_startdate: "2022-08-05",
      task_type: "SentenceTracking",
      testee_idx: 1699,
      trainingtask_idx: 19566,
    },
    {
      task_dayofweek: "월,화,수,목,금",
      task_enddate: "2022-08-18",
      task_generatedate: "2022-08-05",
      task_language: "한국어",
      task_level: 6,
      task_reculsivecount: 3,
      task_startdate: "2022-08-04",
      task_type: "VisualCounting",
      testee_idx: 1699,
      trainingtask_idx: 19565,
    },
    {
      task_dayofweek: null,
      task_enddate: null,
      task_generatedate: null,
      task_language: null,
      task_level: null,
      task_reculsivecount: null,
      task_startdate: null,
      task_type: null,
      testee_idx: 2089,
      trainingtask_idx: null,
    },
    {
      task_dayofweek: null,
      task_enddate: null,
      task_generatedate: null,
      task_language: null,
      task_level: null,
      task_reculsivecount: null,
      task_startdate: null,
      task_type: null,
      testee_idx: 3563,
      trainingtask_idx: null,
    },
  ],
  resultList: [
    {
      testee_idx: 1699,
      tr_accuracyrate: 0.9,
      tr_duration: 3099.424,
      tr_startdate: "2022-08-18 10:37:28",
      trainingresult_idx: 367762,
      trainingtask_idx: 19566,
    },
    {
      testee_idx: 1699,
      tr_accuracyrate: 1,
      tr_duration: 2099.424,
      tr_startdate: "2022-08-18 10:37:28",
      trainingresult_idx: 367762,
      trainingtask_idx: 19566,
    },
  ],
  rank: [
    {
      testee_idx: 1699,
      testee_newtraingscore_idx: 1590,
      tts_totalscore: 1000,
      tts_firstscore: 8000,
      tts_firstscore_resetdate: "2022-10-01 22:22:22",
      tts_firstscore_rank: 1,
      tts_secondscore: 500,
      tts_secondscore_resetdate: "2022-10-01 22:22:22",
    },
    {
      testee_idx: 2089,
      testee_newtraingscore_idx: null,
      tts_totalscore: 800,
      tts_firstscore: 300,
      tts_firstscore_resetdate: "2022-10-01 22:22:22",
      tts_firstscore_rank: 4,
      tts_secondscore: 300,
      tts_secondscore_resetdate: "2022-10-01 22:22:22",
    },
    {
      testee_idx: 3563,
      testee_newtraingscore_idx: null,
      tts_totalscore: 670,
      tts_firstscore: 300,
      tts_firstscore_resetdate: "2022-10-01 22:22:22",
      tts_firstscore_rank: 4,
      tts_secondscore: 300,
      tts_secondscore_resetdate: "2022-10-01 22:22:22",
    },
  ],
};

export const NewDummy = [
  {
    ItsMe: true,
    testee_idx: 1699,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p002",
    testee_nickname: "홍길동",
    tts_totalscore: 13864,
    tts_monthscore: 742,
    tts_firstscore: 4220,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: 3973,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 1,
    testeeTaskIdxList: [
      { idx: 17671, listIdx: 0 },
      { idx: 17672, listIdx: 1 },
      { idx: 17673, listIdx: 2 },
      { idx: 17674, listIdx: 3 },
      { idx: 17675, listIdx: 4 },
      { idx: 17676, listIdx: 5 },
      { idx: 17677, listIdx: 6 },
      { idx: 17678, listIdx: 7 },
      { idx: 17679, listIdx: 8 },
      { idx: 17680, listIdx: 9 },
      { idx: 17681, listIdx: 10 },
      { idx: 17682, listIdx: 11 },
      { idx: 17683, listIdx: 12 },
      { idx: 17684, listIdx: 13 },
      { idx: 17685, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 17671, task_name: "SentenceMask", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 17672,
        task_name: "VisualSpan",
        task_type: "Cognitive",
        level: 5,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 3,
        isactive: 1,
        trainingResult: { "2022-12-09": [{ trainingresult_idx: 12, testee_task_idx: 17672, tr_starttime: "2022-12-09", tr_accuracyrate: 0.9, tr_score: 87.5, tr_duration: 36.146, trainingtext_idx: null, tr_feeling: null }] },
      },
      {
        testee_task_idx: 17673,
        task_name: "CategoryFinding",
        task_type: "Reading",
        level: 2,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 2,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 13, testee_task_idx: 17673, tr_starttime: "2022-12-09", tr_accuracyrate: 0.53, tr_score: 41.25, tr_duration: 13.034, trainingtext_idx: 116, tr_feeling: null },
            { trainingresult_idx: 14, testee_task_idx: 17673, tr_starttime: "2022-12-09", tr_accuracyrate: 0.5, tr_score: 37.5, tr_duration: 8.232, trainingtext_idx: 167, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 17674, task_name: "VisualCounting", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17675, task_name: "KeywordFinding", task_type: "Reading", level: 5, dayofweek: "화,목", language: "한국어", reculsivecount: 3, isactive: 1, trainingResult: {} },
      { testee_task_idx: 17676, task_name: "TMT", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17677, task_name: "Stroop", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17678, task_name: "SaccadeTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17679, task_name: "PursuitTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17680, task_name: "AntiTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 17681,
        task_name: "WordOrdering",
        task_type: "Reading",
        level: 5,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 4,
        isactive: 1,
        trainingResult: { "2022-12-09": [{ trainingresult_idx: 15, testee_task_idx: 17681, tr_starttime: "2022-12-09", tr_accuracyrate: 0.66, tr_score: 59.2, tr_duration: 13.146, trainingtext_idx: null, tr_feeling: null }] },
      },
      { testee_task_idx: 17682, task_name: "SentenceTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17683, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17684, task_name: "ExerciseVertical", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 17685, task_name: "ExerciseHJump", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 1960,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p003",
    testee_nickname: "김김김",
    tts_totalscore: 841,
    tts_monthscore: 193,
    tts_firstscore: 437,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: 367,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 2,
    testeeTaskIdxList: [
      { idx: 20176, listIdx: 0 },
      { idx: 20177, listIdx: 1 },
      { idx: 20178, listIdx: 2 },
      { idx: 20179, listIdx: 3 },
      { idx: 20180, listIdx: 4 },
      { idx: 20181, listIdx: 5 },
      { idx: 20182, listIdx: 6 },
      { idx: 20183, listIdx: 7 },
      { idx: 20184, listIdx: 8 },
      { idx: 20185, listIdx: 9 },
      { idx: 20186, listIdx: 10 },
      { idx: 20187, listIdx: 11 },
      { idx: 20188, listIdx: 12 },
      { idx: 20189, listIdx: 13 },
      { idx: 20190, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 20176, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20177, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 20178,
        task_name: "CategoryFinding",
        task_type: "Reading",
        level: 7,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 2,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 10, testee_task_idx: 20178, tr_starttime: "2022-12-09", tr_accuracyrate: 0, tr_score: -25, tr_duration: 1.078, trainingtext_idx: 78, tr_feeling: null },
            { trainingresult_idx: 11, testee_task_idx: 20178, tr_starttime: "2022-12-09", tr_accuracyrate: 1, tr_score: 100, tr_duration: 7.658, trainingtext_idx: 10, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 20179, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20180, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20181, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20182, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20183, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20184, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20185, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 20186,
        task_name: "WordOrdering",
        task_type: "Reading",
        level: 7,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 2,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 8, testee_task_idx: 20186, tr_starttime: "2022-12-09", tr_accuracyrate: 0.49, tr_score: 38.8, tr_duration: 4.202, trainingtext_idx: null, tr_feeling: null },
            { trainingresult_idx: 9, testee_task_idx: 20186, tr_starttime: "2022-12-09", tr_accuracyrate: 0.84, tr_score: 80.8, tr_duration: 19.73, trainingtext_idx: null, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 20187, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20188, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20189, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 20190, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 2089,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "j",
    testee_nickname: "김김",
    tts_totalscore: 230,
    tts_monthscore: 230,
    tts_firstscore: 230,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: 230,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 3,
    testeeTaskIdxList: [
      { idx: 21946, listIdx: 0 },
      { idx: 21947, listIdx: 1 },
      { idx: 21948, listIdx: 2 },
      { idx: 21949, listIdx: 3 },
      { idx: 21950, listIdx: 4 },
      { idx: 21951, listIdx: 5 },
      { idx: 21952, listIdx: 6 },
      { idx: 21953, listIdx: 7 },
      { idx: 21954, listIdx: 8 },
      { idx: 21955, listIdx: 9 },
      { idx: 21956, listIdx: 10 },
      { idx: 21957, listIdx: 11 },
      { idx: 21958, listIdx: 12 },
      { idx: 21959, listIdx: 13 },
      { idx: 21960, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 21946, task_name: "SentenceMask", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21947, task_name: "VisualSpan", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 21948,
        task_name: "CategoryFinding",
        task_type: "Reading",
        level: 6,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 2,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 1, testee_task_idx: 21948, tr_starttime: "2022-12-09", tr_accuracyrate: 0.56, tr_score: 45, tr_duration: 32.727, trainingtext_idx: 78, tr_feeling: null },
            { trainingresult_idx: 2, testee_task_idx: 21948, tr_starttime: "2022-12-09", tr_accuracyrate: 0.36, tr_score: 20, tr_duration: 7.569, trainingtext_idx: 196, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 21949, task_name: "VisualCounting", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 21950,
        task_name: "KeywordFinding",
        task_type: "Reading",
        level: 6,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 3,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 5, testee_task_idx: 21950, tr_starttime: "2022-12-09", tr_accuracyrate: 0, tr_score: -25, tr_duration: 1.4, trainingtext_idx: 141, tr_feeling: null },
            { trainingresult_idx: 6, testee_task_idx: 21950, tr_starttime: "2022-12-09", tr_accuracyrate: 0.5, tr_score: 37.5, tr_duration: 6.268, trainingtext_idx: 17, tr_feeling: null },
            { trainingresult_idx: 7, testee_task_idx: 21950, tr_starttime: "2022-12-09", tr_accuracyrate: 0.5, tr_score: 37.5, tr_duration: 9.825, trainingtext_idx: 93, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 21951, task_name: "TMT", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21952, task_name: "Stroop", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21953, task_name: "SaccadeTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21954, task_name: "PursuitTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21955, task_name: "AntiTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      {
        testee_task_idx: 21956,
        task_name: "WordOrdering",
        task_type: "Reading",
        level: 6,
        dayofweek: "월,화,수,목,금",
        language: "한국어",
        reculsivecount: 2,
        isactive: 1,
        trainingResult: {
          "2022-12-09": [
            { trainingresult_idx: 3, testee_task_idx: 21956, tr_starttime: "2022-12-09", tr_accuracyrate: 0.83, tr_score: 79.6, tr_duration: 22.21, trainingtext_idx: null, tr_feeling: null },
            { trainingresult_idx: 4, testee_task_idx: 21956, tr_starttime: "2022-12-09", tr_accuracyrate: 0.48, tr_score: 37.6, tr_duration: 4.378, trainingtext_idx: null, tr_feeling: null },
          ],
        },
      },
      { testee_task_idx: 21957, task_name: "SentenceTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21958, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21959, task_name: "ExerciseVertical", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 21960, task_name: "ExerciseHJump", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 2842,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "7",
    testee_nickname: "디어베베물티슈",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 31891, listIdx: 0 },
      { idx: 31892, listIdx: 1 },
      { idx: 31893, listIdx: 2 },
      { idx: 31894, listIdx: 3 },
      { idx: 31895, listIdx: 4 },
      { idx: 31896, listIdx: 5 },
      { idx: 31897, listIdx: 6 },
      { idx: 31898, listIdx: 7 },
      { idx: 31899, listIdx: 8 },
      { idx: 31900, listIdx: 9 },
      { idx: 31901, listIdx: 10 },
      { idx: 31902, listIdx: 11 },
      { idx: 31903, listIdx: 12 },
      { idx: 31904, listIdx: 13 },
      { idx: 31905, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 31891, task_name: "SentenceMask", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31892, task_name: "VisualSpan", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31893, task_name: "CategoryFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31894, task_name: "VisualCounting", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31895, task_name: "KeywordFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31896, task_name: "TMT", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31897, task_name: "Stroop", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31898, task_name: "SaccadeTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31899, task_name: "PursuitTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31900, task_name: "AntiTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31901, task_name: "WordOrdering", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31902, task_name: "SentenceTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31903, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31904, task_name: "ExerciseVertical", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 31905, task_name: "ExerciseHJump", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3449,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p004",
    testee_nickname: "백산수",
    tts_totalscore: 2064,
    tts_monthscore: 0,
    tts_firstscore: 64,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: 64,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 4,
    testeeTaskIdxList: [
      { idx: 40111, listIdx: 0 },
      { idx: 40112, listIdx: 1 },
      { idx: 40113, listIdx: 2 },
      { idx: 40114, listIdx: 3 },
      { idx: 40115, listIdx: 4 },
      { idx: 40116, listIdx: 5 },
      { idx: 40117, listIdx: 6 },
      { idx: 40118, listIdx: 7 },
      { idx: 40119, listIdx: 8 },
      { idx: 40120, listIdx: 9 },
      { idx: 40121, listIdx: 10 },
      { idx: 40122, listIdx: 11 },
      { idx: 40123, listIdx: 12 },
      { idx: 40124, listIdx: 13 },
      { idx: 40125, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 40111, task_name: "SentenceMask", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40112, task_name: "VisualSpan", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40113, task_name: "CategoryFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40114, task_name: "VisualCounting", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40115, task_name: "KeywordFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40116, task_name: "TMT", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40117, task_name: "Stroop", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40118, task_name: "SaccadeTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40119, task_name: "PursuitTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40120, task_name: "AntiTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40121, task_name: "WordOrdering", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40122, task_name: "SentenceTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40123, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40124, task_name: "ExerciseVertical", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40125, task_name: "ExerciseHJump", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3450,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p005",
    testee_nickname: "크리넥스곽티슈",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 40126, listIdx: 0 },
      { idx: 40127, listIdx: 1 },
      { idx: 40128, listIdx: 2 },
      { idx: 40129, listIdx: 3 },
      { idx: 40130, listIdx: 4 },
      { idx: 40131, listIdx: 5 },
      { idx: 40132, listIdx: 6 },
      { idx: 40133, listIdx: 7 },
      { idx: 40134, listIdx: 8 },
      { idx: 40135, listIdx: 9 },
      { idx: 40136, listIdx: 10 },
      { idx: 40137, listIdx: 11 },
      { idx: 40138, listIdx: 12 },
      { idx: 40139, listIdx: 13 },
      { idx: 40140, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 40126, task_name: "SentenceMask", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40127, task_name: "VisualSpan", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40128, task_name: "CategoryFinding", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40129, task_name: "VisualCounting", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40130, task_name: "KeywordFinding", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40131, task_name: "TMT", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40132, task_name: "Stroop", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40133, task_name: "SaccadeTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40134, task_name: "PursuitTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40135, task_name: "AntiTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40136, task_name: "WordOrdering", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40137, task_name: "SentenceTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40138, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40139, task_name: "ExerciseVertical", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40140, task_name: "ExerciseHJump", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3488,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p006",
    testee_nickname: "박격포",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 40666, listIdx: 0 },
      { idx: 40667, listIdx: 1 },
      { idx: 40668, listIdx: 2 },
      { idx: 40669, listIdx: 3 },
      { idx: 40670, listIdx: 4 },
      { idx: 40671, listIdx: 5 },
      { idx: 40672, listIdx: 6 },
      { idx: 40673, listIdx: 7 },
      { idx: 40674, listIdx: 8 },
      { idx: 40675, listIdx: 9 },
      { idx: 40676, listIdx: 10 },
      { idx: 40677, listIdx: 11 },
      { idx: 40678, listIdx: 12 },
      { idx: 40679, listIdx: 13 },
      { idx: 40680, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 40666, task_name: "SentenceMask", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40667, task_name: "VisualSpan", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40668, task_name: "CategoryFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40669, task_name: "VisualCounting", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40670, task_name: "KeywordFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40671, task_name: "TMT", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40672, task_name: "Stroop", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40673, task_name: "SaccadeTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40674, task_name: "PursuitTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40675, task_name: "AntiTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40676, task_name: "WordOrdering", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40677, task_name: "SentenceTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40678, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40679, task_name: "ExerciseVertical", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40680, task_name: "ExerciseHJump", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3489,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p007",
    testee_nickname: "타노스",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 40681, listIdx: 0 },
      { idx: 40682, listIdx: 1 },
      { idx: 40683, listIdx: 2 },
      { idx: 40684, listIdx: 3 },
      { idx: 40685, listIdx: 4 },
      { idx: 40686, listIdx: 5 },
      { idx: 40687, listIdx: 6 },
      { idx: 40688, listIdx: 7 },
      { idx: 40689, listIdx: 8 },
      { idx: 40690, listIdx: 9 },
      { idx: 40691, listIdx: 10 },
      { idx: 40692, listIdx: 11 },
      { idx: 40693, listIdx: 12 },
      { idx: 40694, listIdx: 13 },
      { idx: 40695, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 40681, task_name: "SentenceMask", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40682, task_name: "VisualSpan", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40683, task_name: "CategoryFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40684, task_name: "VisualCounting", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40685, task_name: "KeywordFinding", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40686, task_name: "TMT", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40687, task_name: "Stroop", task_type: "Cognitive", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40688, task_name: "SaccadeTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40689, task_name: "PursuitTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40690, task_name: "AntiTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40691, task_name: "WordOrdering", task_type: "Reading", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40692, task_name: "SentenceTracking", task_type: "Tracking", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40693, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40694, task_name: "ExerciseVertical", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 40695, task_name: "ExerciseHJump", task_type: "Exercise", level: 4, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3563,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "약간좀긴유저의아이디",
    testee_nickname: "약간좀긴유저의이름",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 41746, listIdx: 0 },
      { idx: 41747, listIdx: 1 },
      { idx: 41748, listIdx: 2 },
      { idx: 41749, listIdx: 3 },
      { idx: 41750, listIdx: 4 },
      { idx: 41751, listIdx: 5 },
      { idx: 41752, listIdx: 6 },
      { idx: 41753, listIdx: 7 },
      { idx: 41754, listIdx: 8 },
      { idx: 41755, listIdx: 9 },
      { idx: 41756, listIdx: 10 },
      { idx: 41757, listIdx: 11 },
      { idx: 41758, listIdx: 12 },
      { idx: 41759, listIdx: 13 },
      { idx: 41760, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 41746, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41747, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41748, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41749, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41750, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41751, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41752, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41753, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41754, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41755, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41756, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41757, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41758, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41759, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41760, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3564,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "애매하게긴아이디",
    testee_nickname: "애매한유저이름",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 41761, listIdx: 0 },
      { idx: 41762, listIdx: 1 },
      { idx: 41763, listIdx: 2 },
      { idx: 41764, listIdx: 3 },
      { idx: 41765, listIdx: 4 },
      { idx: 41766, listIdx: 5 },
      { idx: 41767, listIdx: 6 },
      { idx: 41768, listIdx: 7 },
      { idx: 41769, listIdx: 8 },
      { idx: 41770, listIdx: 9 },
      { idx: 41771, listIdx: 10 },
      { idx: 41772, listIdx: 11 },
      { idx: 41773, listIdx: 12 },
      { idx: 41774, listIdx: 13 },
      { idx: 41775, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 41761, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41762, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41763, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41764, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41765, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41766, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41767, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41768, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41769, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41770, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41771, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41772, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41773, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41774, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 41775, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3859,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p008",
    testee_nickname: "p008",
    tts_totalscore: 16,
    tts_monthscore: 0,
    tts_firstscore: 0,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: 0,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 5,
    testeeTaskIdxList: [
      { idx: 45946, listIdx: 0 },
      { idx: 45947, listIdx: 1 },
      { idx: 45948, listIdx: 2 },
      { idx: 45949, listIdx: 3 },
      { idx: 45950, listIdx: 4 },
      { idx: 45951, listIdx: 5 },
      { idx: 45952, listIdx: 6 },
      { idx: 45953, listIdx: 7 },
      { idx: 45954, listIdx: 8 },
      { idx: 45955, listIdx: 9 },
      { idx: 45956, listIdx: 10 },
      { idx: 45957, listIdx: 11 },
      { idx: 45958, listIdx: 12 },
      { idx: 45959, listIdx: 13 },
      { idx: 45960, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 45946, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45947, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45948, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45949, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45950, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45951, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45952, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45953, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45954, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45955, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45956, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45957, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45958, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45959, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 45960, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3996,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "abc",
    testee_nickname: "abc",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 47866, listIdx: 0 },
      { idx: 47867, listIdx: 1 },
      { idx: 47868, listIdx: 2 },
      { idx: 47869, listIdx: 3 },
      { idx: 47870, listIdx: 4 },
      { idx: 47871, listIdx: 5 },
      { idx: 47872, listIdx: 6 },
      { idx: 47873, listIdx: 7 },
      { idx: 47874, listIdx: 8 },
      { idx: 47875, listIdx: 9 },
      { idx: 47876, listIdx: 10 },
      { idx: 47877, listIdx: 11 },
      { idx: 47878, listIdx: 12 },
      { idx: 47879, listIdx: 13 },
      { idx: 47880, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 47866, task_name: "SentenceMask", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47867, task_name: "VisualSpan", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47868, task_name: "CategoryFinding", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47869, task_name: "VisualCounting", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47870, task_name: "KeywordFinding", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47871, task_name: "TMT", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47872, task_name: "Stroop", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47873, task_name: "SaccadeTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47874, task_name: "PursuitTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47875, task_name: "AntiTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47876, task_name: "WordOrdering", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47877, task_name: "SentenceTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47878, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47879, task_name: "ExerciseVertical", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47880, task_name: "ExerciseHJump", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3997,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "abc1",
    testee_nickname: "abc",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 47881, listIdx: 0 },
      { idx: 47882, listIdx: 1 },
      { idx: 47883, listIdx: 2 },
      { idx: 47884, listIdx: 3 },
      { idx: 47885, listIdx: 4 },
      { idx: 47886, listIdx: 5 },
      { idx: 47887, listIdx: 6 },
      { idx: 47888, listIdx: 7 },
      { idx: 47889, listIdx: 8 },
      { idx: 47890, listIdx: 9 },
      { idx: 47891, listIdx: 10 },
      { idx: 47892, listIdx: 11 },
      { idx: 47893, listIdx: 12 },
      { idx: 47894, listIdx: 13 },
      { idx: 47895, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 47881, task_name: "SentenceMask", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47882, task_name: "VisualSpan", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47883, task_name: "CategoryFinding", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47884, task_name: "VisualCounting", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47885, task_name: "KeywordFinding", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47886, task_name: "TMT", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47887, task_name: "Stroop", task_type: "Cognitive", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47888, task_name: "SaccadeTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47889, task_name: "PursuitTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47890, task_name: "AntiTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47891, task_name: "WordOrdering", task_type: "Reading", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47892, task_name: "SentenceTracking", task_type: "Tracking", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47893, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47894, task_name: "ExerciseVertical", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47895, task_name: "ExerciseHJump", task_type: "Exercise", level: 3, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3998,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "abc21",
    testee_nickname: "abc",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 47896, listIdx: 0 },
      { idx: 47897, listIdx: 1 },
      { idx: 47898, listIdx: 2 },
      { idx: 47899, listIdx: 3 },
      { idx: 47900, listIdx: 4 },
      { idx: 47901, listIdx: 5 },
      { idx: 47902, listIdx: 6 },
      { idx: 47903, listIdx: 7 },
      { idx: 47904, listIdx: 8 },
      { idx: 47905, listIdx: 9 },
      { idx: 47906, listIdx: 10 },
      { idx: 47907, listIdx: 11 },
      { idx: 47908, listIdx: 12 },
      { idx: 47909, listIdx: 13 },
      { idx: 47910, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 47896, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47897, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47898, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47899, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47900, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47901, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47902, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47903, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47904, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47905, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47906, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47907, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47908, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47909, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47910, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 3999,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "abc212",
    testee_nickname: "abc",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 47911, listIdx: 0 },
      { idx: 47912, listIdx: 1 },
      { idx: 47913, listIdx: 2 },
      { idx: 47914, listIdx: 3 },
      { idx: 47915, listIdx: 4 },
      { idx: 47916, listIdx: 5 },
      { idx: 47917, listIdx: 6 },
      { idx: 47918, listIdx: 7 },
      { idx: 47919, listIdx: 8 },
      { idx: 47920, listIdx: 9 },
      { idx: 47921, listIdx: 10 },
      { idx: 47922, listIdx: 11 },
      { idx: 47923, listIdx: 12 },
      { idx: 47924, listIdx: 13 },
      { idx: 47925, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 47911, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47912, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47913, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47914, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47915, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47916, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47917, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47918, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47919, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47920, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47921, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47922, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47923, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47924, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47925, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 4000,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "a123",
    testee_nickname: "123124",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 47926, listIdx: 0 },
      { idx: 47927, listIdx: 1 },
      { idx: 47928, listIdx: 2 },
      { idx: 47929, listIdx: 3 },
      { idx: 47930, listIdx: 4 },
      { idx: 47931, listIdx: 5 },
      { idx: 47932, listIdx: 6 },
      { idx: 47933, listIdx: 7 },
      { idx: 47934, listIdx: 8 },
      { idx: 47935, listIdx: 9 },
      { idx: 47936, listIdx: 10 },
      { idx: 47937, listIdx: 11 },
      { idx: 47938, listIdx: 12 },
      { idx: 47939, listIdx: 13 },
      { idx: 47940, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 47926, task_name: "SentenceMask", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47927, task_name: "VisualSpan", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47928, task_name: "CategoryFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47929, task_name: "VisualCounting", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47930, task_name: "KeywordFinding", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47931, task_name: "TMT", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47932, task_name: "Stroop", task_type: "Cognitive", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47933, task_name: "SaccadeTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47934, task_name: "PursuitTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47935, task_name: "AntiTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47936, task_name: "WordOrdering", task_type: "Reading", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47937, task_name: "SentenceTracking", task_type: "Tracking", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47938, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47939, task_name: "ExerciseVertical", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 47940, task_name: "ExerciseHJump", task_type: "Exercise", level: 7, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 4157,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "abc123124",
    testee_nickname: "abc123124",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 50176, listIdx: 0 },
      { idx: 50177, listIdx: 1 },
      { idx: 50178, listIdx: 2 },
      { idx: 50179, listIdx: 3 },
      { idx: 50180, listIdx: 4 },
      { idx: 50181, listIdx: 5 },
      { idx: 50182, listIdx: 6 },
      { idx: 50183, listIdx: 7 },
      { idx: 50184, listIdx: 8 },
      { idx: 50185, listIdx: 9 },
      { idx: 50186, listIdx: 10 },
      { idx: 50187, listIdx: 11 },
      { idx: 50188, listIdx: 12 },
      { idx: 50189, listIdx: 13 },
      { idx: 50190, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 50176, task_name: "SentenceMask", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50177, task_name: "VisualSpan", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50178, task_name: "CategoryFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50179, task_name: "VisualCounting", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50180, task_name: "KeywordFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50181, task_name: "TMT", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50182, task_name: "Stroop", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50183, task_name: "SaccadeTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50184, task_name: "PursuitTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50185, task_name: "AntiTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50186, task_name: "WordOrdering", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50187, task_name: "SentenceTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50188, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50189, task_name: "ExerciseVertical", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50190, task_name: "ExerciseHJump", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 4162,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p009",
    testee_nickname: "p009",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 50251, listIdx: 0 },
      { idx: 50266, listIdx: 1 },
      { idx: 50252, listIdx: 2 },
      { idx: 50267, listIdx: 3 },
      { idx: 50253, listIdx: 4 },
      { idx: 50268, listIdx: 5 },
      { idx: 50254, listIdx: 6 },
      { idx: 50269, listIdx: 7 },
      { idx: 50255, listIdx: 8 },
      { idx: 50270, listIdx: 9 },
      { idx: 50256, listIdx: 10 },
      { idx: 50271, listIdx: 11 },
      { idx: 50257, listIdx: 12 },
      { idx: 50272, listIdx: 13 },
      { idx: 50258, listIdx: 14 },
      { idx: 50273, listIdx: 15 },
      { idx: 50259, listIdx: 16 },
      { idx: 50274, listIdx: 17 },
      { idx: 50260, listIdx: 18 },
      { idx: 50275, listIdx: 19 },
      { idx: 50261, listIdx: 20 },
      { idx: 50276, listIdx: 21 },
      { idx: 50262, listIdx: 22 },
      { idx: 50277, listIdx: 23 },
      { idx: 50263, listIdx: 24 },
      { idx: 50278, listIdx: 25 },
      { idx: 50264, listIdx: 26 },
      { idx: 50279, listIdx: 27 },
      { idx: 50265, listIdx: 28 },
      { idx: 50280, listIdx: 29 },
    ],
    taskList: [
      { testee_task_idx: 50251, task_name: "SentenceMask", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50266, task_name: "SentenceMask", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50252, task_name: "VisualSpan", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50267, task_name: "VisualSpan", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50253, task_name: "CategoryFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50268, task_name: "CategoryFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50254, task_name: "VisualCounting", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50269, task_name: "VisualCounting", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50255, task_name: "KeywordFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50270, task_name: "KeywordFinding", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50256, task_name: "TMT", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50271, task_name: "TMT", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50257, task_name: "Stroop", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50272, task_name: "Stroop", task_type: "Cognitive", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50258, task_name: "SaccadeTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50273, task_name: "SaccadeTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50259, task_name: "PursuitTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50274, task_name: "PursuitTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50260, task_name: "AntiTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50275, task_name: "AntiTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50261, task_name: "WordOrdering", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50276, task_name: "WordOrdering", task_type: "Reading", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50262, task_name: "SentenceTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50277, task_name: "SentenceTracking", task_type: "Tracking", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50263, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50278, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50264, task_name: "ExerciseVertical", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50279, task_name: "ExerciseVertical", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50265, task_name: "ExerciseHJump", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50280, task_name: "ExerciseHJump", task_type: "Exercise", level: 5, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
  {
    ItsMe: false,
    testee_idx: 4163,
    agency_ID: "jeong",
    agency_name: "jeong.",
    user_ID: "p10",
    testee_nickname: "p10",
    tts_totalscore: null,
    tts_monthscore: null,
    tts_firstscore: null,
    tts_firstscore_resetdate: "22-10-13",
    tts_secondscore: null,
    tts_secondscore_resetdate: "22-10-19",
    tier: "브론즈",
    rank: 6,
    testeeTaskIdxList: [
      { idx: 50281, listIdx: 0 },
      { idx: 50282, listIdx: 1 },
      { idx: 50283, listIdx: 2 },
      { idx: 50284, listIdx: 3 },
      { idx: 50285, listIdx: 4 },
      { idx: 50286, listIdx: 5 },
      { idx: 50287, listIdx: 6 },
      { idx: 50288, listIdx: 7 },
      { idx: 50289, listIdx: 8 },
      { idx: 50290, listIdx: 9 },
      { idx: 50291, listIdx: 10 },
      { idx: 50292, listIdx: 11 },
      { idx: 50293, listIdx: 12 },
      { idx: 50294, listIdx: 13 },
      { idx: 50295, listIdx: 14 },
    ],
    taskList: [
      { testee_task_idx: 50281, task_name: "SentenceMask", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50282, task_name: "VisualSpan", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50283, task_name: "CategoryFinding", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50284, task_name: "VisualCounting", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50285, task_name: "KeywordFinding", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50286, task_name: "TMT", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50287, task_name: "Stroop", task_type: "Cognitive", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 3, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50288, task_name: "SaccadeTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50289, task_name: "PursuitTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50290, task_name: "AntiTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50291, task_name: "WordOrdering", task_type: "Reading", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50292, task_name: "SentenceTracking", task_type: "Tracking", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50293, task_name: "ExerciseHorizontal", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50294, task_name: "ExerciseVertical", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
      { testee_task_idx: 50295, task_name: "ExerciseHJump", task_type: "Exercise", level: 6, dayofweek: "월,화,수,목,금", language: "한국어", reculsivecount: 2, isactive: 0, trainingResult: {} },
    ],
  },
] as TesteeType[];
